name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ github.ref == 'refs/heads/main' && 'ipu-main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Add yarn globally
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Build and Test
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Running production build"
            sudo cp .env.production .env
            npx nx run-many --target=generate-prod 
            npx nx run-many --target=build --production
          else
            echo "Running development build"
            sudo cp .env.development .env
            npx nx run-many --target=generate-dev 
            npx nx run-many --target=build --development
          fi

      - name: Deploy
        run: |
          - sudo cp -R dist/* /var/www/ipu-main/html
