name: CI

on:
  push:
    branches:
      - main
      - dev 
jobs:
  build:
    runs-on: ${{ github.ref == 'refs/heads/main' && 'ipu-main' || 'reg-educon-dev' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'
      
      - name: Add yarn globally
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Build and Test
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Running production build"
            CI=false
            yarn build
          else
            echo "Running development build"
            yarn build:dev
          fi

      - name: Deploy
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            cp -a ~/frontend-main/actions-runner/_work/ipu-main/ipu-main/build/. /var/www/ipu-main/html
          else
            cp -a ~/front-registration-runner/actions-runner/_work/registrationEducon/registrationEducon/dist/. /var/www/registrationdev.educon.uz/html
          fi
